# Generated by Django 3.1.4 on 2021-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=150)),
                ('nama', models.CharField(max_length=150)),
                ('alamat', models.CharField(max_length=150)),
                ('prodi', models.CharField(max_length=150)),
            ],
        ),
    ]
