# Generated by Django 3.1.4 on 2021-02-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai_Data_Latih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_class', models.CharField(max_length=150)),
                ('node', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
